# Usar una imagen base de Python
FROM python:3.8

# Variable de entorno
ENV FLASK_APP micro_service.py

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de requisitos y instalar dependencias
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos de tu aplicación Flask
COPY . /app

# Definir el comando para ejecutar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]
